name: gaussian_splatting
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.8
  - python=3.9
  - pip
  - pip:
    # - submodules/diff-gaussian-rasterization
    # - submodules/diff-gaussian-rasterization_contrastive_f
    # - submodules/diff-gaussian-rasterization-depth
    # - submodules/simple-knn
    # - third_party/segment-anything
    - dearpygui
    - opencv-python
    - open-clip-torch
    - joblib
    - torch
    - torchaudio
    - torchvision
    - tqdm
    - hdbscan
    - matplotlib
    - plyfile
