name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda
  - plyfile
  - python=3.9
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - hdbscan
  - matplotlib
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/diff-gaussian-rasterization_contrastive_f
    - submodules/diff-gaussian-rasterization-depth
    - submodules/simple-knn
    - third_party/segment-anything
    - dearpygui
    - opencv-python
    - open-clip-torch
    - joblib
